// Code generated by "stringer -type=rank"; DO NOT EDIT.

package deck

import "strconv"

const _rank_name = "acetwothreefourfivesixseveneightninetenjackqueenking"

var _rank_index = [...]uint8{0, 3, 6, 11, 15, 19, 22, 27, 32, 36, 39, 43, 48, 52}

func (i rank) String() string {
	i -= 1
	if i < 0 || i >= rank(len(_rank_index)-1) {
		return "rank(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _rank_name[_rank_index[i]:_rank_index[i+1]]
}
