// Code generated by "stringer -type=suit"; DO NOT EDIT.

package deck

import "strconv"

const _suit_name = "clubsdiamondsheartsspades"

var _suit_index = [...]uint8{0, 5, 13, 19, 25}

func (i suit) String() string {
	if i < 0 || i >= suit(len(_suit_index)-1) {
		return "suit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _suit_name[_suit_index[i]:_suit_index[i+1]]
}
